on:
  pull_request:
  push:
  workflow_dispatch:  

jobs:
  spellcheck:
    name: "Spell Check"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v2.4.0
      with:
        version: 8
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i
    - name: Spellcheck
      run: pnpm spellcheck
